vim.keymap.set('n', '<C-h>', '<Cmd>BufferPrevious<CR>')
vim.keymap.set('n', '<C-l>', '<Cmd>BufferNext<CR>')
vim.keymap.set('n', '<C-w>', '<Cmd>BufferClose<CR>')
vim.keymap.set('n', '<Leader>h', '<Cmd>BufferMovePrevious<CR>')
vim.keymap.set('n', '<Leader>l', '<Cmd>BufferMoveNext<CR>')
vim.keymap.set('n', '<Leader>;', '<Cmd>BufferGoto 1<CR>')
vim.keymap.set('n', '<Leader>1', '<Cmd>BufferGoto 2<CR>')
vim.keymap.set('n', '<Leader>2', '<Cmd>BufferGoto 2<CR>')
vim.keymap.set('n', '<Leader>3', '<Cmd>BufferGoto 3<CR>')
vim.keymap.set('n', '<Leader>4', '<Cmd>BufferGoto 4<CR>')
vim.keymap.set('n', '<Leader>5', '<Cmd>BufferGoto 5<CR>')
vim.keymap.set('n', '<Leader>6', '<Cmd>BufferGoto 6<CR>')
vim.keymap.set('n', '<Leader>7', '<Cmd>BufferGoto 7<CR>')
vim.keymap.set('n', '<Leader>8', '<Cmd>BufferGoto 8<CR>')
vim.keymap.set('n', '<Leader>9', '<Cmd>BufferGoto 9<CR>')
vim.keymap.set('n', "<Leader>'", '<Cmd>BufferLast<CR>')
vim.keymap.set('n', '<Leader>p', '<Cmd>BufferPickDelete<CR>')
vim.keymap.set('n', '<Leader>r', '<Cmd>BufferRestore<CR>')
vim.keymap.set('n', '<Leader>P', '<Cmd>BufferPin<CR>')
vim.keymap.set('n', '<Leader>bb', '<Cmd>BufferOrderByBufferNumber<CR>')
vim.keymap.set('n', '<Leader>bd', '<Cmd>BufferOrderByDirectory<CR>')
vim.keymap.set('n', '<Leader>bl', '<Cmd>BufferOrderByLanguage<CR>')
vim.keymap.set('n', '<Leader>bw', '<Cmd>BufferOrderByWindowNumber<CR>')

