# editorconfig-vim
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# colorschemes
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
colorscheme gruvbox
'''

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='gruvbox'
'''

# Gitのステータスをファイル左横に表示するやつ
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
nnoremap ]h <Plug>(GitGutterNextHunk)
nnoremap [h <Plug>(GitGutterPrevHunk)
nnoremap ghs <Plug>(GitGutterStageHunk)
nnoremap ghu <Plug>(GitGutterUndoHunk)
nnoremap ghp <Plug>(GitGutterPreviewHunk)
'''

# vim上でGit操作可能にするやつ
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <Leader>ga :G add %:p<CR><CR>
nnoremap <Leader>gc :G commit<CR><CR>
nnoremap <Leader>gs :G status<CR>
nnoremap <Leader>gp :G push<CR>
nnoremap <Leader>gd :G diff<CR>
nnoremap <Leader>gl :G log<CR>
nnoremap <Leader>glo :G log --oneline<CR>
nnoremap <Leader>gb :G blame<CR>
'''

# ファイラー
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
nnoremap <Leader>e <cmd>Fern . -reveal=%<CR>
'''

# fuzzy finder
[[plugins]]
repo = 'junegunn/fzf'
build = 'bash install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
rev = 'release/rpc'
hook_add = '''
nnoremap <silent>//     <cmd>FzfPreviewLinesRpc<CR>
nnoremap <silent><C-f>  <cmd>FzfPreviewBufferLinesRpc<CR>
nnoremap <silent><C-p>  <cmd>FzfPreviewProjectFilesRpc<CR>

"nnoremap <silent>//     :BLines<CR>
"nnoremap <silent><C-f>  :Lines<CR>
"nnoremap <silent><C-p>  :Files<CR>
'''

# フォーカス移動を自由自在にするやつ
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
noremap  <Leader>f <Plug>(easymotion-bd-f)
nnoremap <Leader>f <Plug>(easymotion-overwin-f)
nnoremap <Leader>s <Plug>(easymotion-overwin-f2)
noremap  <Leader>L <Plug>(easymotion-bd-jk)
nnoremap <Leader>L <Plug>(easymotion-overwin-line)
noremap  <Leader>w <Plug>(easymotion-bd-w)
nnoremap <Leader>w <Plug>(easymotion-overwin-w)
'''

# yank範囲をハイライトするやつ
[[plugins]]
repo = 'machakann/vim-highlightedyank'

# 選択範囲を段階的に広げるやつ
[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap V <Plug>(expand_region_shrink)
'''

# アイコン提供するやつ
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# タブ操作を簡単にするやつ
[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
nnoremap <C-q>      <Cmd>BufferClose<CR>
nnoremap <C-h>      <Cmd>BufferPrevious<CR>
nnoremap <C-l>      <Cmd>BufferNext<CR>
nnoremap <Leader>h  <Cmd>BufferMovePrevious<CR>
nnoremap <Leader>l  <Cmd>BufferMoveNext<CR>
nnoremap <Leader>;  <Cmd>BufferGoto 1<CR>
nnoremap <Leader>1  <Cmd>BufferGoto 1<CR>
nnoremap <Leader>2  <Cmd>BufferGoto 2<CR>
nnoremap <Leader>3  <Cmd>BufferGoto 3<CR>
nnoremap <Leader>4  <Cmd>BufferGoto 4<CR>
nnoremap <Leader>5  <Cmd>BufferGoto 5<CR>
nnoremap <Leader>6  <Cmd>BufferGoto 6<CR>
nnoremap <Leader>7  <Cmd>BufferGoto 7<CR>
nnoremap <Leader>8  <Cmd>BufferGoto 8<CR>
nnoremap <Leader>9  <Cmd>BufferGoto 9<CR>
nnoremap <Leader>'  <Cmd>BufferLast<CR>
nnoremap <Leader>p  <Cmd>BufferPick<CR>
nnoremap <Leader>p  <Cmd>BufferPickDelete<CR>
nnoremap <Leader>r  <Cmd>BufferRestore<CR>
nnoremap <Leader>P  <Cmd>BufferPin<CR>
nnoremap <Leader>bb <Cmd>BufferOrderByBufferNumber<CR>
nnoremap <Leader>bd <Cmd>BufferOrderByDirectory<CR>
nnoremap <Leader>bl <Cmd>BufferOrderByLanguage<CR>
nnoremap <Leader>bw <Cmd>BufferOrderByWindowNumber<CR>
'''

# JSONを扱いやすくするやつ
[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
set conceallevel=2
set concealcursor=niv
let g:vim_json_syntax_conceal = 0
'''

# 「閉じ」文字を補完するやつ
[[plugins]]
repo = 'cohama/lexima.vim'

# 「囲み」文字を簡単に操作するやつ
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト・解除を簡単にするやつ
[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'

nmap <C-c> <Plug>NERDCommenterToggle
vmap <C-c> <Plug>NERDCommenterToggle<CR>gv
'''

# 縦スクロールバーを表示するやつ
[[plugins]]
repo = 'dstein64/nvim-scrollview'

# ハイライトを補強するやつ
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 1
# hook_post_update = 'TSUpdate'
hook_add = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'go',
        'html',
        'javascript',
        'json',
        'python',
        'ruby',
        'rust',
        'toml',
        'typescript',
    },
    highlight = {
        enable = true,
        disable = {},
    },
}
EOF
'''

