add_newline = true
command_timeout = 1000

[battery]
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 20
style = "bold yellow"

[cmd_duration]
disabled = true

[git_branch]
symbol = " "

[git_status]
style = "bold purple"

[ruby]
symbol = " "
